# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

include ApplicationHelper

# 2013
load_appearance("7 February 2013", "Michael Moore, Humza Yousaf, Lord Falconer, Mary Macleod, Brian Souter")
load_appearance("31 January 2013", "Sayeeda Warsi, Alan Johnson, Dom Joly, Zoe Williams, James Delingpole")
load_appearance("24 January 2013", "Anna Soubry, Ben Bradshaw, Menzies Campbell, Ian Hislop, Angela Epstein")
load_appearance("17 January 2013", "Nigel Farage, Mary Beard, Grant Shapps, Caroline Flint, Roland Rudd")
load_appearance("10 January 2013", "Ed Davey, John Prescott, Nadine Dorries, John Bird, Camilla Cavendish")

# 2012
load_appearance("13 December 2012", "Justine Greening, Stella Creasy, Lord Bilimoria, Will Self, Peter Hitchens")
load_appearance("6 December 2012", "Francis Maude, Andy Burnham, Tim Farron, Lionel Barber, Leanne Wood")
load_appearance("29 November 2012", "Patrick McLoughlin, Chris Bryant, Simon Jenkins, Neil Wallis, Charlotte Church")
load_appearance("22 November 2012", "Iain Duncan Smith, Yvette Cooper, Charles Kennedy, Deborah Meaden, Owen Jones")
load_appearance("15 November 2012", "Chris Grayling, Harriet Harman, Nigel Farage, Tessa Munt, Moray MacLennan")
load_appearance("8 November 2012", "Damian Green, Chuka Umunna, Shirley Williams, David Blanchflower, Jane Moore")
load_appearance("1 November 2012", "David Miliband, Kwasi Kwarteng, Shami Chakrabarti, Jerry Springer, Colleen Graffy")
load_appearance("25 October 2012", "Vince Cable, Emily Thornberry, Claire Perry, Paul Nuttall, Mehdi Hasan")
load_appearance("18 October 2012", "Nicola Sturgeon, Ruth Davidson, Margaret Curran, Alan Cochrane, Mark Serwotka")
load_appearance("11 October 2012", "Grant Shapps, Caroline Flint, Simon Hughes, Cristina Odone, Benjamin Zephaniah")
load_appearance("4 October 2012", "Kenneth Clarke, Douglas Alexander, Susan Kramer, Willie Walsh, Janet Street-Porter")
load_appearance("27 September 2012", "Danny Alexander, Harriet Harman, Jacob Rees-Mogg, Kirstie Allsopp, Steve Coogan")
load_appearance("5 July 2012", "Ed Davey, Alan Johnson, Louise Mensch, Dominic Lawson, John Lydon")
load_appearance("28 June 2012", "Justine Greening, Tessa Jowell, Paddy Ashdown, Tony Robinson, Terry Smith")
load_appearance("21 June 2012", "Kenneth Clarke, Andy Burnham, Len McCluskey, Ruth Lea, Julie White")
load_appearance("14 June 2012", "Grant Shapps, Emily Thornberry, Tim Farron, Peter Hitchens, Greg Dyke")
load_appearance("7 June 2012", "Charles Kennedy, Johann Lamont, Lord Forsyth, Alex Neil, Melanie Phillips, Alan Cumming")
load_appearance("31 May 2012", "Alan Duncan, Stella Creasy, Mark Oaten, Fraser Nelson, Victoria Coren")
load_appearance("24 May 2012", "David Willetts, John Prescott, Caroline Lucas, Griff Rhys Jones, Minette Marrin")
load_appearance("17 May 2012", "Maria Miller, Peter Hain, Leanne Wood, Kelvin MacKenzie, John O'Farrell")
load_appearance("10 May 2012", "Caroline Spelman, Chris Bryant, Lord Oakeshott, Mary Beard, Peter Oborne")
load_appearance("3 May 2012", "Iain Duncan Smith, Harriet Harman, Menzies Campbell, Theo Paphitis, Mark Serwotka")
load_appearance("26 April 2012", "Chris Grayling, Diane Abbott, Simon Hughes, Nigel Farage, Polly Toynbee")
load_appearance("19 April 2012", "Sayeeda Warsi, Yvette Cooper, Tim Farron, George Galloway, David Aaronovitch")
load_appearance("29 March 2012", "Sarah Teather, Douglas Alexander, Anna Soubry, Simon Jenkins, Alexei Sayle")
load_appearance("22 March 2012", "Vince Cable, Chuka Umunna, David Davis, Melissa Kite, Marina Lewycka")
load_appearance("15 March 2012", "Willie Rennie, Ruth Davidson, Frank Field, Humza Yousaf, Janet Street-Porter")
load_appearance("08 March 2012", "Eric Pickles, Caroline Flint, Will Young, Janice Atkinson-Small, Will Self")
load_appearance("01 March 2012", "John Redwood, Rachel Reeves, Jo Swinson, David Starkey, Clarke Carlisle")
load_appearance("23 February 2012", "Ed Vaizey, Emily Thornberry, Paul Nuttall, Cristina Odone, Simon Schama")
load_appearance("16 February 2012", "Ken Clarke, John Prescott, Susan Kramer, Julie Meyer, Owen Jones")
load_appearance("09 February 2012", "Philip Hammond, Shirley Williams, Alistair Campbell, Steve Coogan, Ann Leslie")
load_appearance("02 February 2012", "Alan Duncan, Sadiq Khan, Digby Jones, Phil Redmond, Emma Boon")
load_appearance("26 January 2012", "Jeremy Browne, David Lammy, Elizabeth Truss, Mark Steel, Melanie Philips")
load_appearance("19 January 2012", "Sayeeda Warsi, Stephen Twigg, Caroline Lucas, Germaine Greer, Charles Moore")
load_appearance("12 January 2012", "Justine Greening, Douglas Alexander, Paddy Ashdown, Nicola Sturgeon, Kelvin Mackenzie")

# 2011
load_appearance("8 December 2011", "Tristram Hunt, Claire Perry, Constance Briscoe, Simon Wolfson, Medhi Hasan")
load_appearance("1 December 2011", "Ken Clarke, Chuka Umunna, Deborah Meaden, David Frum, Mary Bousted")
load_appearance("24 November 2011", "Chris Huhne, Liz Kendall, Daniel Hannan, Justin King, Jimmy Wales")
load_appearance("17 November 2011", "Grant Shapps, Chris Bryant, Elin Jones, Will Hutton, Simon Jenkins")
load_appearance("17 November 2011", "Grant Shapps, Chris Bryant, Elin Jones, Will Hutton, Simon Jenkins")
load_appearance("10 November 2011", "Michael Moore, Rachel Reeves, Nadine Dorries, Colin Blakemore, Stephen Pollard")
load_appearance("3 November 2011", "Theresa May, Ed Balls, Shirley Williams, Peter Hitchens, Benjamin Zephaniah")
load_appearance("27 October 2011", "Iain Duncan Smith, Gloria De Piero, Nigel Farage, Jo Swinson, Julian Fellowes")
load_appearance("20 October 2011", "Alistair Carmichael, Margaret Curran, Jacob Rees-Mogg, Brian Cox, Mike Russell")
load_appearance("13 October 2011", "Andrew Lansley, Ken Livingstone, Sarah Sands, Dr Phil Hammond, Mark Littlewood")
load_appearance("6 October 2011", "Sayeeda Warsi, Andy Burnham, Charles Kennedy, Jane Moore, Billy Bragg")
load_appearance("29 September 2011", "Grant Shapps, Tim Farron, Caroline Flint, Janet Street-Porter, Peter Oborne")
load_appearance("22 September 2011", "Vince Cable, Harriet Harman, Priti Patel, Ian Hislop, Justine Roberts")
load_appearance("15 September 2011", "Owen Paterson, Diane Abbott, Nigel Dodds, Martina Anderson, Nicola Horlick")
load_appearance("8 September 2011", "Liam Fox, David Miliband, Richard Perle, Tariq Ali, Bonnie Greer, Christina Schmidt")
load_appearance("11 August 2011", "David Davis, Lord Prescott, Brian Paddick, Fraser Nelson, Camila Batmanghelidjh, Archbishop John Sentamu")
load_appearance("7 July 2011", "Chris Grayling, Douglas Alexander, Baroness Williams, Hugh Grant, Jon Gaunt")
load_appearance("30 June 2011", "Philip Hammond, John Denham, Polly Toynbee, Richard Lambert, Christine Blower")
load_appearance("23 June 2011", "Norman Baker, John Redwood, Rachel Reeves, Fern Britton, David Mitchell")
load_appearance("16 June 2011", "Michael Moore, Alex Salmond, Lord Forsyth, Margaret Curran, Sir Tom Hunter")
load_appearance("9 June 2011", "Andrew Mitchell, Charles Clarke, Jo Swinson, Germaine Greer, Peter Hitchens")
load_appearance("2 June 2011", "Stephen Dorrell, Alan Johnson, Elfyn Llwyd, Sir Simon Jenkins, Julia Hartley-Brewer")
load_appearance("26 May 2011", "Jeremy Browne, Hilary Benn, Louise Bagshawe, Charlotte Harris, Christopher Meyer")
load_appearance("19 May 2011", "Ken Clarke, Jack Straw, Shami Chakrabarti, Melanie Phillips")
load_appearance("12 May 2011", "Vince Cable, David Blunkett, Anna Soubry, James O'Brien, Max Mosley")
load_appearance("5 May 2011", "Philip Hammond, Andy Burnham, Paddy Ashdown, Yasmin Alibhai-Brown, Douglas Murray")
load_appearance("14 April 2011", "Chris Huhne, Michael Howard, Peter Hain, Alex Salmond, Cristina Odone")
load_appearance("7 April 2011", "Jeremy Hunt, Caroline Flint, Jo Swinson, Robert Winston, Simon Callow")
load_appearance("31 March 2011", "Boris Johnson, Sarah Teather, Dianne Abbott, Clive Anderson, Mark Serwotka")
load_appearance("24 March 2011", "Danny Alexander, Ken Livingstone, Rory Stewart, Niall Ferguson, Bianca Jagger")
load_appearance("17 March 2011", "Sayeeda Warsi, Simon Hughes, Chris Bryant, Caroline Lucas, Kelvin MacKenzie")
load_appearance("10 March 2011", "Michael Moore, Douglas Alexander, Annabel Goldie, Nicola Sturgeon, Patrick Harvie, Nick Ferrari")
load_appearance("3 March 2011", "Iain Duncan Smith, Margaret Beckett, Lord Malloch Brown, David Starkey, Liam Halligan")
load_appearance("24 February 2011", "Cheryl Gillan, Peter Hain, Shirley Williams, Elfyn Llwyd, Janet Street-Porter, Fraser Nelson")
load_appearance("17 February 2011", "Vince Cable, Yvette Cooper, Michael Heseltine, Nigel Farage, Victoria Barnsley")
load_appearance("10 February 2011", "Francis Maude, Menzies Campbell, Jacqui Smith, Mehdi Hasan, Douglas Murray")
load_appearance("3 February 2011", "Andy Burnham, Damian Green, Clare Short, Melanie Phillips, Noreena Hertz")
load_appearance("27 January 2011", "Chris Huhne, Chuka Umunna, Edwina Currie, Will Self, Katie Hopkins")
load_appearance("20 January 2011", "Caroline Spelman, Simon Hughes, Alastair Campbell, George Galloway, Clarke Carlisle")
load_appearance("13 January 2011", "Michael Gove, Charles Kennedy, Diane Abbott, Jeanette Winterson, James Caan")